export const monoSemanticTokens = {
  colors: {
    'bg.canvas': { value: '{colors.palette.canvas}' },
    'bg.surface': { value: '{colors.palette.white}' },
    'bg.subtle': { value: '{colors.palette.subtle}' },
    'bg.inverse': { value: '{colors.palette.ink}' },
    'fg.default': { value: '{colors.palette.ink}' },
    'fg.secondary': { value: '{colors.palette.secondary}' },
    'fg.muted': { value: '{colors.palette.muted}' },
    'fg.inverse': { value: '{colors.palette.white}' },
    'border.structural': { value: '{colors.palette.divider}' },
    'border.control': { value: '{colors.palette.muted}' },
    'border.strong': { value: '{colors.palette.secondary}' },
    'action.primary.bg': { value: '{colors.palette.ink}' },
    'action.primary.hoverBg': { value: '{colors.palette.secondary}' },
    'action.primary.fg': { value: '{colors.palette.white}' },
    'action.secondary.bg': { value: '{colors.palette.white}' },
    'action.secondary.hoverBg': { value: '{colors.palette.subtle}' },
    'action.disabled.bg': { value: '{colors.palette.divider}' },
    'action.disabled.fg': { value: '{colors.palette.secondary}' },
    'focus.ring': { value: '{colors.palette.ink}' },
    'selection.bg': { value: '{colors.palette.divider}' },
    'overlay.scrim': { value: 'rgb(23 23 23 / 48%)' },
  },
}
