name: CI

on:
  workflow_dispatch:
  push:
    branches: [master, 'release/**']
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.2.2
        with:
          fetch-depth: 0

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .nvmrc
          cache: ${{ github.event_name == 'pull_request' && '' || 'pnpm' }}
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Verify
        run: pnpm run verify

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        with:
          args: >-
            -Dsonar.qualitygate.wait=true
            -Dsonar.qualitygate.timeout=300
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}

      - name: Sonar Issue Inspection
        if: ${{ github.event_name == 'pull_request' }}
        run: pnpm run sonar:issues:local
